# Generated by Django 6.0.1 on 2026-01-08 15:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_domain",
                    models.CharField(
                        default="psu.palawan.edu.ph",
                        help_text="(e.g., psu.palawan.edu.ph)",
                        max_length=100,
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(
                        help_text="The sender email address", max_length=254
                    ),
                ),
                (
                    "from_name",
                    models.CharField(
                        default="College of Sciences",
                        help_text="Display name for sender",
                        max_length=200,
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        default="smtp.gmail.com",
                        help_text="SMTP server host",
                        max_length=200,
                    ),
                ),
                (
                    "smtp_port",
                    models.IntegerField(default=587, help_text="SMTP server port"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Configuration",
                "verbose_name_plural": "Email Configuration",
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("subject", models.CharField(max_length=300)),
                ("header_message", models.CharField(max_length=200)),
                ("body_content", models.TextField(help_text="Main email body content")),
                (
                    "is_predefined",
                    models.BooleanField(
                        default=False, help_text="Predefined templates cannot be edited"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_predefined", "name"],
            },
        ),
        migrations.CreateModel(
            name="CertificateBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_certificates", models.IntegerField(default=0)),
                ("successful_sends", models.IntegerField(default=0)),
                ("failed_sends", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_details", models.TextField(blank=True, null=True)),
                (
                    "template_used",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mailer.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Certificate Batches",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(db_index=True, max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("certificate_filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "sent_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "template_used",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="mailer.emailtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["-sent_at", "status"],
                        name="mailer_emai_sent_at_050100_idx",
                    )
                ],
            },
        ),
    ]
