# Generated by Django 6.0.1 on 2026-01-13 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="college",
            field=models.CharField(
                choices=[
                    ("CS", "College of Sciences"),
                    ("CBA", "College of Business and Accountancy"),
                ],
                default=0,
                help_text="College this template belongs to",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "college",
                    models.CharField(
                        choices=[
                            ("CS", "College of Sciences"),
                            ("CBA", "College of Business and Accountancy"),
                        ],
                        help_text="College this user belongs to",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
