# Generated by Django 6.0.1 on 2026-01-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0002_emailtemplate_college_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="college",
            field=models.CharField(
                choices=[
                    ("CS", "College of Sciences"),
                    ("CBA", "College of Business and Accountancy"),
                    ("CAH", "College of Arts and Humanities"),
                ],
                help_text="College this template belongs to",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="college",
            field=models.CharField(
                choices=[
                    ("CS", "College of Sciences"),
                    ("CBA", "College of Business and Accountancy"),
                    ("CAH", "College of Arts and Humanities"),
                ],
                help_text="College this user belongs to",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailtemplate",
            unique_together={("name", "college")},
        ),
    ]
