"""
Django settings for projectsite project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-n16*e!ou-m9chb9*f$p_7!0=+jkr@_)7!atvru5f=t9*gs0ob^"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['csmail.pythonanywhere.com', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    'mailer', # Main app
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "projectsite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "projectsite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    # },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = (
    BASE_DIR / 'static',
)

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# File uploads
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# Message tags
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-error',
}

# Authentication settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'send_certificates'
LOGOUT_REDIRECT_URL = 'login'

# ============================================================
# TESTING MODE CONFIGURATION
# ============================================================
# Set CERTIFICATE_TESTING_MODE = True in settings.py to enable testing mode
# In testing mode: filename (removed extension) becomes email address directly without name validation
# Example: "john.doe.pdf" -> "john.doe@gmail.com"
# ============================================================
CERTIFICATE_TESTING_MODE = False
CERTIFICATE_TEST_EMAIL_NAME = "testuser"
CERTIFICATE_TEST_EMAIL_DOMAIN = "gmail.com"

# College Details
COLLEGES = {
    'CS': {
        'name': 'College of Sciences',
        'logo': 'https://github.com/n3mo1101/pn-certificate-mailer/blob/main/projectsite/static/img/cs_logo.png?raw=true',
        'email': 'cs@psu.palawan.edu.ph',
        'social': 'https://www.facebook.com/CollegeOfSciencesPSU/'
    },
    'CBA': {
        'name': 'College of Business and Accountancy',
        'logo': 'https://github.com/n3mo1101/pn-certificate-mailer/blob/main/projectsite/static/img/cba_logo.png?raw=true',
        'email': 'cba@psu.palawan.edu.ph',
        'social': 'https://www.facebook.com/cba.tycoons'
    },
    'CAH': {
        'name': 'College of Arts and Humanities',
        'logo': 'https://github.com/n3mo1101/pn-certificate-mailer/blob/main/projectsite/static/img/cah_logo.png?raw=true',
        'email': 'cah@psu.palawan.edu.ph',
        'social': 'https://www.facebook.com/CAHpamilya'
    }
}

# Generate choices for model fields
COLLEGE_CHOICES = [(code, info['name']) for code, info in COLLEGES.items()]